library(readxl)
student_baseline_performance <- read_excel("C:\\Users\\edutabuser\\Downloads\\student_baseline_performance.xlsx")
View(student_baseline_performance)
is.na(student_baseline_performance)
sum(is.na(student_baseline_performance))
na.omit(student_baseline_performance)
mean(student_baseline_performance)
mean(student_baseline_performance$MathQ1, na.rm=TRUE)
library(mice)
md.pattern(student_baseline_performance)
complete.cases(student_baseline_performance)
colSums(is.na(student_baseline_performance))
rowsum(is.na(student_baseline_performance))
na.omit(student_baseline_performance)
na.exclude(student_baseline_performance)
library(tidyr)
na.fail(student_baseline_performance)